/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const GameResult = IDL.Record({
  'userId' : UserId,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const UserStats = IDL.Record({
  'userId' : UserId,
  'highestLevel' : IDL.Nat,
  'bestScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'totalGames' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getMyHistory' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getMyStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const GameResult = IDL.Record({
    'userId' : UserId,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const UserStats = IDL.Record({
    'userId' : UserId,
    'highestLevel' : IDL.Nat,
    'bestScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'totalGames' : IDL.Nat,
  });
  
  return IDL.Service({
    'getMyHistory' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getMyStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };